-- 做T收益/波段收益增加买入价、买入量、卖出价、卖出量四个字段，
-- 之前只存了拼好的 desc 文案（如"3.98买4000→4.01卖4000"），历史记录回填时
-- 拿不回原始的买卖价格和数量，导致「做T收益」编辑区打开历史记录时这四个输入框总是空的。

ALTER TABLE stock_t_records ADD COLUMN IF NOT EXISTS buy_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE stock_t_records ADD COLUMN IF NOT EXISTS buy_shares DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE stock_t_records ADD COLUMN IF NOT EXISTS sell_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE stock_t_records ADD COLUMN IF NOT EXISTS sell_shares DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE stock_swing_records ADD COLUMN IF NOT EXISTS buy_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE stock_swing_records ADD COLUMN IF NOT EXISTS buy_shares DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE stock_swing_records ADD COLUMN IF NOT EXISTS sell_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE stock_swing_records ADD COLUMN IF NOT EXISTS sell_shares DOUBLE PRECISION NOT NULL DEFAULT 0;
